name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: ""
      project_name:
        description: Project valid identifier name (defaults to github.event.repository.name )
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  
  reusable_workflow_job:
    env:
        NAMESPACE: ${{ inputs.namespace == "" && format('cns-{0}', inputs.project_name) || inputs.namespace }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      
      - uses: hmarr/debug-action@v2
      - run: |
          echo "Hello ${{ inputs.username }}"
          echo "github.event_name ===> ${{ github.event_name }} "
          echo "github.event.pull_request.merged ===> ${{ github.event.pull_request.merged }}"
          echo "github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push' ===> ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push' }}"
      - run: echo env.NAMESPACE = ${{ env.NAMESPACE }}

