name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: hmarr/debug-action@v2
      - run: |
          echo Hello ${{ inputs.username }}
          echo github.event_name ===> ${{ github.event_name }} 
          echo github.event.pull_request.merged ===> ${{ github.event.pull_request.merged }}
          echo github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push' ===> ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push' }}
          
      
