name: test merge

on:
   workflow_dispatch:

   pull_request:
    types: [ opened, synchronize, closed ]
    branches:
      - "main"    
   release:
    types: [ published ]
    branches:
      - "main"

jobs:
  call-workflow-2-in-local-repo:
    if: |
      github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'push' 
      ||
      github.event_name == 'release'
    uses: ./.github/workflows/reusable-workflow.yaml #simulates my buidl and push image
    with:
      username: mona
