name: test merge

on:
   workflow_dispatch:
   
   push:
     branches:
      - "main"    
      
   pull_request:
     types: [ opened, synchronize, closed ]
     branches:
       - "main"    
      
   release:
     types: [ published ]
     branches:
       - "main"

jobs:
  call-workflow-2-in-local-repo:
    if: |
      github.event_name == 'pull_request' && github.event.pull_request.merged == false ||
      github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) ||
      github.event_name == 'release'

    uses: ./.github/workflows/reusable-workflow.yaml #simulates my buidl and push image
    with:
      username: mona
