name: w2

on:
  workflow_run:
    workflows: 
      - w1
    types:
      - completed
      
jobs:
  on-success:
    runs-on: ubuntu-latest
    needs: github.event.workflow_run.jobs.outputs

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo ${{ github.event.workflow_run.jobs.outputs.myoutput}}

